# Generated by Django 2.2.1 on 2019-12-01 05:55

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191201_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address_to_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_to_company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_to_country',
            field=models.CharField(blank=True, default='US', max_length=2, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_to_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_to_state',
            field=localflavor.us.models.USStateField(blank=True, max_length=2, null=True, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_to_street1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_to_street2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="address cont'd"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_to_zip',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='zip code'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_pharmacy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_pharmacy_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='insurance_member_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='insurance_member_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='refills_left',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shopify_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='truepill_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
