# Generated by Django 2.2.1 on 2019-12-01 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20191201_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='insurer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='myapp.Insurer'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='medications',
            field=models.ManyToManyField(null=True, related_name='profiles', to='myapp.Medication'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prescriber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='myapp.Prescriber'),
        ),
    ]
