# Generated by Django 2.2.1 on 2019-12-01 06:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20191201_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='other_medications',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='patient_known_allergies',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_to_company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='To company'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_to_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='To name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='insurer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='myapp.Insurer', verbose_name='Insurer'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='medications',
            field=models.ManyToManyField(null=True, related_name='profiles', to='myapp.Medication', verbose_name='Medications'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prescriber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='myapp.Prescriber', verbose_name='Prescriber'),
        ),
    ]
